### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mauromi** [batiste/sdl2-opengl-es#2]
I have followed your steps in README and i'm stopped in the last step (fedora 16) :

/usr/bin/ld: /tmp/ccUtpjS7.o: undefined reference to symbol 'sqrtf@@GLIBC_2.2.5'
/usr/bin/ld: note: 'sqrtf@@GLIBC_2.2.5' is defined in DSO /lib64/libm.so.6 so try adding it to the linker command line
/lib64/libm.so.6: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make: **\* [eglbuild] Error 1

**Comment by mauromi** [comment]
fix with -lm in Makefile

but now i'm stucked with this specific fedora error:
/usr/lib64/libglapi.so.0: undefined reference to `security_get_boolean_active'
/usr/lib64/libglapi.so.0: undefined reference to`is_selinux_enabled'
/usr/lib64/libglapi.so.0: undefined reference to `security_get_boolean_pending'

**Comment by batiste** [comment]
It seems to be an issue with Mesa GL:

https://bugzilla.redhat.com/show_bug.cgi?id=383471

**Comment by mauromi** [comment]
I have applyed this patch https://bugzilla.redhat.com/attachment.cgi?id=576624&action=diff . Recompile and install mesa 7.11.2 with option ./configure --enable-gles2, Fix the problem.

So, now i can compile your project.
But i get this error, when run the executable:

Unable to create window
0.00 frames per second

Can i get some debug error from sdl2 ?
thanks

**Comment by mauromi** [comment]
CHECK_SDL() give me these errors :

SDL ERROR: file:common.c line:914 error:No OpenGL support in video driver
SDL ERROR: file:common.c line:918 error:Invalid window

but glxinfo output say :

glxinfo | grep render
direct rendering: Yes
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile

**Comment by mauromi** [comment]
well i have installed latest SDL from hg and now i get only this from CHECK_SDL() :

SDL ERROR: file:common.c line:918 error:Invalid window

**Comment by mauromi** [comment]
ok, i'm stuck here
http://bugzilla.libsdl.org/show_bug.cgi?id=1495
and is not anymore related to compiling your project
